version: '3.4'
services:
  db:
    #build: ./database
    image: mpacris/greenthumb-hub-database:1.0
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    restart: always
    volumes:
      - db-data:/var/lib/mysql
  api:
    #build: ./backend
    image: mpacris/greenthumb-hub-backend:1.0
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - "db"
    command: >
      sh -c "flask db upgrade && gunicorn -b 0.0.0.0 app:app"

  frontend:
    #build: ./frontend
    image: mpacris/greenthumb-hub-frontend:1.0
    ports:
      - 80:80
    depends_on:
      - "api"
    restart: always
volumes:
  db-data:
