"""trying to get table back

Revision ID: 97185644fca7
Revises: 10a9ad6b0f1b
Create Date: 2023-06-09 13:54:34.749749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97185644fca7'
down_revision = '10a9ad6b0f1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserGardens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('garden_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['garden_id'], ['garden.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'user_id', 'garden_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserGardens')
    # ### end Alembic commands ###
