"""going back on harvest db

Revision ID: 91d6ed92ec1b
Revises: af7965336d6e
Create Date: 2023-06-15 19:09:57.374167

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '91d6ed92ec1b'
down_revision = 'af7965336d6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserGardens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('garden_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['garden_id'], ['garden.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'user_id', 'garden_id')
    )
    op.drop_table('usergardens')
    with op.batch_alter_table('harvest', schema=None) as batch_op:
        batch_op.drop_column('plant_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('harvest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plant_id', mysql.INTEGER(), autoincrement=False, nullable=True))

    op.create_table('usergardens',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('garden_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['garden_id'], ['garden.id'], name='usergardens_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='usergardens_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('UserGardens')
    # ### end Alembic commands ###
