"""needed to add to the harvest table

Revision ID: e1bed24347a0
Revises: 91d6ed92ec1b
Create Date: 2023-06-15 23:19:54.253241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1bed24347a0'
down_revision = '91d6ed92ec1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserGardens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('garden_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['garden_id'], ['garden.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'user_id', 'garden_id')
    )
    with op.batch_alter_table('harvest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plant_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('task_completed', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('harvest', schema=None) as batch_op:
        batch_op.drop_column('task_completed')
        batch_op.drop_column('plant_id')

    op.drop_table('UserGardens')
    # ### end Alembic commands ###
